// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Luna - Seu Ciclo, Sua Vida 🌙",
  description: "O app brasileiro de saúde feminina mais completo. Rastreie seu ciclo, conecte-se com outras mulheres e cuide da sua saúde.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <Script id="error-handler" strategy="beforeInteractive">
          {`
            // Suprime erros de desenvolvimento do Next.js/Turbopack
            const IGNORABLE_ERRORS = ['Failed to load chunk', 'hmr-client', '__nextjs_original-stack-frames', 'turbopack'];
            
            window.addEventListener('error', (e) => {
              if (IGNORABLE_ERRORS.some(pattern => e.message?.includes(pattern))) {
                e.preventDefault();
                console.debug('[Dev] Erro de desenvolvimento ignorado');
              }
            });
            
            window.addEventListener('unhandledrejection', (e) => {
              const msg = e.reason?.message || String(e.reason);
              if (IGNORABLE_ERRORS.some(pattern => msg?.includes(pattern))) {
                e.preventDefault();
                console.debug('[Dev] Promise rejection de desenvolvimento ignorada');
              }
            });
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
